# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Vladimir'

steps:

- task: NuGetCommand@2
  displayName: 'restore NuGet, nuget task'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'restore NuGet, DotNetCoreCLI task'
  inputs:
    command: 'restore'
    projects: '**/*/*.csproj'

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    arguments: '--configuration Debug'
